### ISSUE TITLE
Solving the Laplacian matrix equation

### ISSUE THREAD

**Issue by bmershon** [bmershon/laplacian-meshes#1]
Currently, the only points that move are the manually edited anchors, which exactly update while the rest of the mesh is unchanged.

Least-squares solution found for each coordinate (X1, X2, X3).

``` python
    mesh.VPos[anchorsIdx, :] = anchors
    L = getLaplacianMatrixUmbrella(mesh, anchorsIdx)
    delta = np.array(L.dot(mesh.VPos)) # with K anchor rows


    # update mesh with least-squares solution
    for k in range(3):
        mesh.VPos[:, k] = lsqr(L, delta[:, k])[0]
```

The problem is either here, or in how I set up the [Laplacian matrix](https://github.com/bmershon/laplacian-meshes/blob/master/LaplacianMesh.py#L22-L45).

**Comment by ctralie** [comment]
Nice code and great use of list comprehensions.  The problem is on line 69

mesh.VPos[anchorsIdx, :] = anchors

This line perfectly explains the bug you're having.  Think carefully about the sequence of your code and why doing that there is a mistake.  Let me know if you have any conceptual questions around that

**Comment by bmershon** [comment]
Thanks!

Homer's really let himself go:

![homer-sag](https://cloud.githubusercontent.com/assets/3190945/14588709/845c83da-049d-11e6-93be-5cf59e57bfef.png)

**If I'm understanding the slides correctly**, I can augment (append to) the delta matrix with the weighted "updated" anchors. These anchors are not really delta coordinates, for they do not represent any notion of curvature), but in the least squared solution their presence will knock other vertices around to preserve local curvature while attempting to keep the mesh faithful to the new set of vertex positions.

_My previous mistake was in updating the actual vertices without augmenting the delta matrix. I essentially cut out the least-squares approximation by creating a system of equations that was NOT overdetermined. Whoops._

I'm a little shaky on how adding a few other vertices here and there for the Homer example can "condition" him (his Laplacian matrix) to keep areas from deforming when we don't want them to. It would seem I need _a lot_ more points, since Homer is sagging "globally" even when I just try to pull his bell and arms down. I'll do some reading and play around more, because I believe my implementation is now correct.

### Solution:

``` py
    L = getLaplacianMatrixUmbrella(mesh, anchorsIdx)
    delta = np.array(L.dot(mesh.VPos))

    for i in range(K):
        delta[N + i, :] = WEIGHT * anchors[i, :]
```
